project_id = "pbtupzbqtuxzznwummep"

[functions.shop-checkout]
verify_jwt = false

[functions.send-confirmation-email]
verify_jwt = false

[functions.send-product-order-confirmation-email]
verify_jwt = false

[functions.order-created-message]
verify_jwt = false

[functions.share-event]
verify_jwt = false

[functions.tracking-redirect]
verify_jwt = false

[functions.create-stripe-checkout-session]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false
