project_id = "usadgrhxgdhjmkznupri"

[functions.shop-checkout]
verify_jwt = false

[functions.send-confirmation-email]
verify_jwt = false

[functions.order-created-message]
verify_jwt = false

[functions.share-event]
verify_jwt = false

[functions.create-stripe-checkout-session]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false
